# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1c71823ade07bb34a8c819272fbf1081f55ed615a9c5026a569e65418d5af2288092b9261e4e2c5e6ed82dd2a92b57e1e88b5bc4ba09806e06056329ecf80d5

test:
  secret_key_base: 222e73609d8a2eb8804bc2cda1e5776c42dc1479c11ba9519b8afa8fcdffc26aa69f338daf1cad0ce57ace369ade34305c92d78675b223cca2d9ae9919d2395f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
